-- USE mozgokep;

-- Adatok felvitele

INSERT INTO filmek (filmCim, bemutatasEve, hosszPercben, ertekeles, leiras, boritokepURL) VALUES 
('Mátrix', 1999, 136, 8.7, 'Volt valaha olyan álmod, amiről azt hitted, valóság? Mi lenne, ha nem tudnál felébredni belőle? Hogy tudnád megkülönböztetni az álmot és a valóságot? Amikor egy gyönyörű idegen bevezeti Neót, a hackert egy veszélyes rejtett világba, rájön a döbbenetes igazságra: a valóság, ami körülveszi, egy gonosz cyber-intelligencia mesteri alkotása. Neo csatlakozik a legendás és veszélyes lázadó harcoshoz, Morpheushoz, hogy elpusztítsák az illúziót, ami rabságban tartja az emberiséget. Innentől minden mozdulat, minden pillanat, minden gondolat maga az életben maradásért folytatott küzdelem – küzdelem a Mátrixból való szabadulásért.', 'https://www.mafab.hu/static/profiles/2014/292/23/3284_46.jpg'),
('Ryan közlegény megmentése', 1998, 169, 8.6, 'A normandiai partraszállás idején három testvér holtan fekszik a csatatéren, a negyedik az ellenséges vonalak mögött rekedt. Miller kapitány és 7 embere feladata lesz, hogy behatoljanak a németek által uralt területre, és hazahozzák a fiút.', 'https://www.mafab.hu/static/profiles/2014/292/23/3883_3.jpg'),
('Chihiro Szellemországban', 2001, 125, 8.6, 'Chihiro egy tízéves akaratos kislány, aki csalódottan fogadja, hogy szüleivel másik városba kell költöznie. Az utazás során eltévednek, és rátalálnak egy sötét alagútra, mely egy elvarázsolt szellemvároshoz vezet. Az üres utcákon fejedelmi lakomától roskadoznak az asztalok. Az éhes szülők mohón vetik rá magukat a finom ételekre, ám amikor felbukkannak szellemváros igazi vacsoravendégei, disznóvá változnak. Az eldugott mesevilág lakói ősi istenek és más csodalények, akik Yubaba, a gonosz boszorkány uralma alatt élnek. Chihiro csak akkor oldozhatja fel szüleit a varázslat alól, ha munkát vállal a banya hatalmas fürdőházában.', 'https://www.mafab.hu/static/2019/162/12/2338_1560336349.8778.jpg'),
('Szentjánosbogarak sírja', 1988, 89, 8.5, 'A Chihiro Szellemországban és A vándorló palota alkotói ezúttal egy szívszorító, igaz történetet tárnak elénk, amely két testvérpár megpróbáltatásait kíséri végig a második világháború végén Japánban. A háborútól sújtott országban Seita és kishúga, Setsuko egy bombázás következtében elveszítik édesanyjukat. Apjuk, aki egy hadihajón szolgál, nem tud a segítségükre sietni. Nagynénjükhöz kerülnek, akiben azonban nem bíznak. Miközben a világ pokollá válik körülöttük, csak egymásra számíthatnak.', 'https://www.mafab.hu/static/profiles/2014/293/04/21339_13.jpg'),
('WALL-E', 2008, 98, 8.4, 'Már többszáz éve, hogy a lakhatatlan Földet elhagyták az emberek, az egész bolygón egy kis robot tevékenykedik csupán, akit valaki bekapcsolava felejtett. WALL-E (Waste Allocation Load Lifter Earth-Class, azaz Watt Lánctalpas Limlom- és Hulladékkezelő Robot az E sorozatból) magányosan gyűjtögeti a szemetet már réges régen, amikor véletlen találkozik a "csinos" Extraterresztriális Vegetáció Analizálóval, EVA-val. EVA ráébred, hogy a szemétszedés közben WALL-E ráakadt a Föld jövőjének kulcsára, így a támaszpontnak veszi az irányt, hogy jelentse a kulcsfontosságú információt. WALL-E a robot után ered, új célt adva ezzel életének.', 'https://www.mafab.hu/static/profiles/2014/293/11/45989_11.jpg'),
('Good Will Hunting', 1997, 126, 8.3, 'Will Hunting Dél-Boston munkásnegyedében él. Keményen dolgozik, amikor éppen nem valamelyik bárban iszik vagy nem kerül valami bajba. Soha nem tanult egyetemen, de fotografikus memóriájának közsönhetően megoldhatatlannak tűnő matematikai feladatokat old meg. Egy újabb kocsmai verekedés után azonban nem tud kibújni a büntetés alól, az egyetlen ember, aki ebben a nehéz helyzetben segíthet neki, Sean McGuire pszichológus.', 'https://www.mafab.hu/static/profiles/2014/292/23/3030_39.jpg'),
('Truman Show', 1998, 103, 8.2, 'Truman Burbank egy szürke kivárosban éli egyszerű életét, átlagos munkája, takaros háza, szép felesége és egy-két titkos vágya van, melyeket csak barátjával tud megosztani. Mégis ő a világ legismertebb embere, akinek mindennapjait az egész világ figyelemmel követi. Neki ugyanis fogalma sincs róla, hogy otthona, a félsziget csak egy díszlet, rokonai, barátai és munkatársai pedig színészek, akik a világ legdrágább valóságshow-jának részei, melynek ő maga a főszereplője. A rendező semmit sem bíz a véletlenre, ám Truman valahogy mégis gyanút fog...', 'https://www.mafab.hu/static/2014/265/43148_1.jpg'),
('Jurassic Park', 1993, 127, 8.2, 'John Hammond, a vállalkozó kedvű, excentrikus milliárdos borostyánba zárt dinoszauruszvérből újraalkotja az őslényeket. Mindössze hónapokkal a tervezett megnyitás előtt meginvitál két jeles dinoszaurusz-szakértőt, Dr. Alan Grantet és Dr. Ellie Sattlert, egyikük szerint azonban a folyamatok csakhamar ellenőrizhetetlenné válnak. Hiába az áttörhetetlennek tűnő biztonsági rendszer, a park tervezői nem számoltak az emberi természet végtelen móhóságával, mely katasztrófához vezethet.', 'https://www.mafab.hu/static/profiles/2014/292/23/2744_13.jpg'),
('Agymanók', 2015, 95, 8.2, 'A serdülőkor általában nem egyszerű, és ezt kénytelen megtapasztalni Riley is. Amikor édesapja új munkát kap San Franciscóban, a lányon vegyes érzelmek lesznek úrrá, köztük az undor, a harag, a szomorúság és a félelem. Az érzelmeket megszemélyesítő Agymanók a lány fejében élnek, azonban nem sokkal a költözés után odabent kitör a káosz. Riley megpróbál pozitív maradni, és meglátni a városban az új élet lehetőségét, de ez nem megy könnyedén...', 'https://www.mafab.hu/static/profiles/2015/64/12/98845.jpg'),
('A vándorló palota', 2004, 119, 8.2, 'Sophie édesapja kalapboltjában dolgozik, és fiatal kora ellenére szórakozásra csak nagyon ritkán jut ideje. Azonban egy nap, amikor a szomszéd városba látogat, találkozik a sármos varázslóval, Howllal. A Puszta borszorkánya félreérti kettejük kapcsolatát, és 90 éves öregasszonnyá változtatja Sophie-t. Az elátkozott Sophie kétségbeesésében a pusztába menekül, ahol rátalál a varázsló vándorló palotájára. Eltitkolva kilétét takaírtónőként kap munkát, és élettel tölti meg az egész kastélyt.', 'https://www.mafab.hu/static/profiles/2014/293/11/44894_10.jpg'),
('Szörny Rt.', 2001, 92, 8.1, 'A gyerekszoba szekrényében szörnyek laknak, ez a gyerekek számára köztudott tény. A szörnyek előmásznak, ijesztgetnek, és minél nagyobb sikításra késztetik az alvó apróságokat. Ám erre komoly indokuk is van - városukat és világukat ugyanis a gyerekek sikolyai látják el energiával. Sulley a legsikeresebb rémisztők közé tartozik, míg barátja, Mike a háttérben munkálkodik. Ám sikeres életük egyszer csak felbolydul, amikor bekövetkezik a legveszélyesebb dolog, ami a szörnyek világában megtörténhet: egy kislány átszökik egy nyitva felejtett ajtón...', 'https://www.mafab.hu/static/profiles/2014/293/10/44022_23.jpg'),
('L''ecsó', 2007, 111, 8.1, 'Remy, a patkány másról sem álmodozik, mint hogy séfként dolgozhasson. Bár a környezete nem rajong az ötletért, mégis belevág a kalaldba, de szembesülnie kell azzal, hogy az emberek uralta világban nem mindenki repes az örömtől, ha megjelenik a konyhában. Végül azonban barátra lel Linguini személyében, és közösem hatalmas sikereket érnek el. Együttműködésüket azonban többen is rossz szemmel nézik.', 'https://www.mafab.hu/static/profiles/2014/293/11/44392_45.jpg');

INSERT INTO mufajok (mufajNev) VALUES
('Dráma'),
('Románc'),
('Vígjáték'),
('Rövidfilm'),
('Krimi'),
('Thriller'),
('Családi'),
('Rejtély'),
('Akció'),
('Fantasy'),
('Kalandfilm'),
('Sci-Fi'),
('Animációs'),
('Történelmi'),
('Horror'),
('Zenés'),
('Valóság-Show'),
('Háborús'),
('Életrajz'),
('Talk-Show'),
('Dokumentumfilm'),
('Musical'),
('Sport'),
('Nyugati'),
('Hírek'),
('Játék-Show'),
('Film-Noir'),
('Felnőtt');

INSERT INTO filmek_mufajok (filmID, mufajID) VALUES
(1,  9),
(1,  12),
(2,  1),
(2,  18),
(3,  13),
(3,  11),
(3,  7),
(4,  13),
(4,  1),
(4,  18),
(5,  13),
(5,  11),
(5,  7),
(6,  1),
(6,  2),
(7,  3),
(7,  1),
(8,  9),
(8,  11),
(8,  12),
(9,  13),
(9,  11),
(9,  3),
(10, 13),
(10, 11),
(10, 7),
(11, 13),
(11, 11),
(11, 3),
(12, 13),
(12, 11),
(12, 3);

INSERT INTO rendezok (rendezoNev) VALUES
('Lana Wachowski'),
('Lilly Wachowski'),
('Steven Spielberg'),
('Hayao Miyazaki'),
('Isao Takahata'),
('Andrew Stanton'),
('Gus Van Sant'),
('Peter Weir'),
('Pete Docter'),
('Ronnie Del Carmen'),
('David Silverman'),
('Lee Unkrich'),
('Brad Bird'),
('Jan Pinkava');

INSERT INTO filmek_rendezok (filmID, rendezoID) VALUES
(1,  1),
(1,  2),
(2,  3),
(3,  4),
(4,  5),
(5,  6),
(6,  7),
(7,  8),
(8,  3),
(9,  9),
(9,  10),
(10, 4),
(11, 9),
(11, 11),
(11, 12),
(12, 13),
(12, 14);

INSERT INTO szineszek (szineszNev) VALUES
('Keanu Reeves'),
('Laurence Fishburne'),
('Carrie-Anne Moss'),
('Hugo Weaving'),
('Tom Hanks'),
('Matt Damon'),
('Tom Sizemore'),
('Rumii Hiiraji'),
('Mizu Irino'),
('Mari Natsuki'),
('Tsutomu Tatsumi'),
('Ayano Shiraishi'),
('Akemi Yamaguchi'),
('Yoshiko Shinohara'),
('Ben Burtt'),
('Elissa Knight'),
('Jeff Garlin'),
('Robin Williams'),
('Ben Affleck'),
('Jim Carrey'),
('Ed Harris'),
('Laura Linney'),
('Sam Neill'),
('Laura Dern'),
('Jeff Goldblum'),
('Richard Attenborough'),
('Amy Poehler'),
('Bill Hader'),
('Lewis Black'),
('Mindy Kaling'),
('Phyllis Smith'),
('Chieko Baishô'),
('Takuya Kimura'),
('Tatsuya Gashûin'),
('Billy Crystal'),
('John Goodman'),
('Mary Gibbs'),
('Steve Buscemi'),
('Brad Garrett'),
('Lou Romano'),
('Patton Oswalt'),
('Ian Holm');

INSERT INTO filmek_szineszek (filmID, szineszID, szereploNev) VALUES
(1,  1,  'Neo'),
(1,  2,  'Morpheus'),
(1,  3,  'Trinity'),
(1,  4,  'Agent Smith'),
(2,  5,  'Private Ryan'),
(2,  6,  'Sergeant Horvath'),
(2,  7,  'Private Reiben'),
(3,  8,  'Chihiro hangja'),
(3,  9,  'Haku hangja'),
(3,  10, 'Yubaba hangja'),
(4,  11, 'Seita hangja'),
(4,  12, 'Setsuko hangja'),
(4,  13, 'Nagynéni hangja'),
(4,  14, 'Anyuka hangja'),
(5,  15, 'WALL-E hangja'),
(5,  16, 'EVE hangja'),
(5,  17, 'Kapitány hangja'),
(6,  18, 'Sean'),
(6,  6,  'Will'),
(6,  19, 'Chuckie'),
(7,  20, 'Truman Burbank'),
(7,  21, 'Christof'),
(7,  22, 'Meryl Burbank'),
(8,  23, 'Grant'),
(8,  24, 'Ellie'),
(8,  25, 'Malcolm'),
(8,  26, 'Hammond'),
(9,  27, 'Derű hangja'),
(9,  28, 'Majré hangja'),
(9,  29, 'Harag hangja'),
(9,  30, 'Undor hangja'),
(9,  31, 'Bánat hangja'),
(10, 32, 'Sophie hangja'),
(10, 33, 'Howl hangja'),
(10, 34, 'Calcifer hangja'),
(11, 35, 'Mike hangja'),
(11, 36, 'Sullivan hangja'),
(11, 37, 'Boo hangja'),
(11, 38, 'Randall hangja'),
(12, 39, 'Gusteau hangja'),
(12, 40, 'Linguini hangja'),
(12, 41, 'Remy hangja'),
(12, 42, 'Skinner hangja');